on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.12.x, 1.13.x]
        platform: [ubuntu-latest]
    name: Run ${{ matrix.go-version }} on ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    env:
      GO111MODULE: on
    steps:
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test
      run: go test -race -v ./...
